name: Android Playground CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - uses: actions/cache@v2
        id: rn-cache
        with:
          path: rn/node_modules
          key: ${{ runner.os }}-${{ hashFiles('rn/package-lock.json') }}

      # Only setup the RN if cache is not available
      - name: set up RN
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          cd rn
          npm install

      # Setup cache for Gradle Wrapper
      - uses: actions/cache@v2
        id: gradle-cache
        with:
          path: |
            /home/runner/.gradle/wrapper
            /home/runner/.gradle/caches/modules-2
          key: ${{ runner.os }}-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}

      # Setup google-service.json is
      - name: Set up Google Service
        env:
          TARGET_FILE: app/google-services.json
          SERVICE_JSON: ${{ secrets.GOOGLE_SERVICE_JSON }}
        run: |
          echo "$SERVICE_JSON" | base64 -d > app/google-services.json
          du $TARGET_FILE
          echo "Google service JSON is extracted to $TARGET_FILE"
          echo "Service: $SERVICE_JSON"

      - name: set up JDK 11
        uses: actions/setup-java@v2.4.0
        with:
          distribution: adopt-openj9
          java-version: '11'

      - name: Build with Gradle
        run: ./gradlew assembleDebug
